/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type Id = {};

export type CreateLayoutResponseDto = {
    id: Id;
};

/** @internal */
export const Id$inboundSchema: z.ZodType<Id, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type Id$Outbound = {};

/** @internal */
export const Id$outboundSchema: z.ZodType<Id$Outbound, z.ZodTypeDef, Id> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Id$ {
    /** @deprecated use `Id$inboundSchema` instead. */
    export const inboundSchema = Id$inboundSchema;
    /** @deprecated use `Id$outboundSchema` instead. */
    export const outboundSchema = Id$outboundSchema;
    /** @deprecated use `Id$Outbound` instead. */
    export type Outbound = Id$Outbound;
}

/** @internal */
export const CreateLayoutResponseDto$inboundSchema: z.ZodType<
    CreateLayoutResponseDto,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        _id: z.lazy(() => Id$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            _id: "id",
        });
    });

/** @internal */
export type CreateLayoutResponseDto$Outbound = {
    _id: Id$Outbound;
};

/** @internal */
export const CreateLayoutResponseDto$outboundSchema: z.ZodType<
    CreateLayoutResponseDto$Outbound,
    z.ZodTypeDef,
    CreateLayoutResponseDto
> = z
    .object({
        id: z.lazy(() => Id$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            id: "_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateLayoutResponseDto$ {
    /** @deprecated use `CreateLayoutResponseDto$inboundSchema` instead. */
    export const inboundSchema = CreateLayoutResponseDto$inboundSchema;
    /** @deprecated use `CreateLayoutResponseDto$outboundSchema` instead. */
    export const outboundSchema = CreateLayoutResponseDto$outboundSchema;
    /** @deprecated use `CreateLayoutResponseDto$Outbound` instead. */
    export type Outbound = CreateLayoutResponseDto$Outbound;
}
