/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateTopicResponseDto = {};

/** @internal */
export const CreateTopicResponseDto$inboundSchema: z.ZodType<
    CreateTopicResponseDto,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type CreateTopicResponseDto$Outbound = {};

/** @internal */
export const CreateTopicResponseDto$outboundSchema: z.ZodType<
    CreateTopicResponseDto$Outbound,
    z.ZodTypeDef,
    CreateTopicResponseDto
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTopicResponseDto$ {
    /** @deprecated use `CreateTopicResponseDto$inboundSchema` instead. */
    export const inboundSchema = CreateTopicResponseDto$inboundSchema;
    /** @deprecated use `CreateTopicResponseDto$outboundSchema` instead. */
    export const outboundSchema = CreateTopicResponseDto$outboundSchema;
    /** @deprecated use `CreateTopicResponseDto$Outbound` instead. */
    export type Outbound = CreateTopicResponseDto$Outbound;
}
