/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetTopicResponseDtoEnvironmentId = {};

export type GetTopicResponseDtoId = {};

export type GetTopicResponseDtoOrganizationId = {};

export type GetTopicResponseDtoKey = {};

export type GetTopicResponseDtoName = {};

export type GetTopicResponseDto = {
    environmentId: GetTopicResponseDtoEnvironmentId;
    id?: GetTopicResponseDtoId | undefined;
    organizationId: GetTopicResponseDtoOrganizationId;
    key: GetTopicResponseDtoKey;
    name: GetTopicResponseDtoName;
    subscribers: Array<string>;
};

/** @internal */
export const GetTopicResponseDtoEnvironmentId$inboundSchema: z.ZodType<
    GetTopicResponseDtoEnvironmentId,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type GetTopicResponseDtoEnvironmentId$Outbound = {};

/** @internal */
export const GetTopicResponseDtoEnvironmentId$outboundSchema: z.ZodType<
    GetTopicResponseDtoEnvironmentId$Outbound,
    z.ZodTypeDef,
    GetTopicResponseDtoEnvironmentId
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTopicResponseDtoEnvironmentId$ {
    /** @deprecated use `GetTopicResponseDtoEnvironmentId$inboundSchema` instead. */
    export const inboundSchema = GetTopicResponseDtoEnvironmentId$inboundSchema;
    /** @deprecated use `GetTopicResponseDtoEnvironmentId$outboundSchema` instead. */
    export const outboundSchema = GetTopicResponseDtoEnvironmentId$outboundSchema;
    /** @deprecated use `GetTopicResponseDtoEnvironmentId$Outbound` instead. */
    export type Outbound = GetTopicResponseDtoEnvironmentId$Outbound;
}

/** @internal */
export const GetTopicResponseDtoId$inboundSchema: z.ZodType<
    GetTopicResponseDtoId,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type GetTopicResponseDtoId$Outbound = {};

/** @internal */
export const GetTopicResponseDtoId$outboundSchema: z.ZodType<
    GetTopicResponseDtoId$Outbound,
    z.ZodTypeDef,
    GetTopicResponseDtoId
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTopicResponseDtoId$ {
    /** @deprecated use `GetTopicResponseDtoId$inboundSchema` instead. */
    export const inboundSchema = GetTopicResponseDtoId$inboundSchema;
    /** @deprecated use `GetTopicResponseDtoId$outboundSchema` instead. */
    export const outboundSchema = GetTopicResponseDtoId$outboundSchema;
    /** @deprecated use `GetTopicResponseDtoId$Outbound` instead. */
    export type Outbound = GetTopicResponseDtoId$Outbound;
}

/** @internal */
export const GetTopicResponseDtoOrganizationId$inboundSchema: z.ZodType<
    GetTopicResponseDtoOrganizationId,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type GetTopicResponseDtoOrganizationId$Outbound = {};

/** @internal */
export const GetTopicResponseDtoOrganizationId$outboundSchema: z.ZodType<
    GetTopicResponseDtoOrganizationId$Outbound,
    z.ZodTypeDef,
    GetTopicResponseDtoOrganizationId
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTopicResponseDtoOrganizationId$ {
    /** @deprecated use `GetTopicResponseDtoOrganizationId$inboundSchema` instead. */
    export const inboundSchema = GetTopicResponseDtoOrganizationId$inboundSchema;
    /** @deprecated use `GetTopicResponseDtoOrganizationId$outboundSchema` instead. */
    export const outboundSchema = GetTopicResponseDtoOrganizationId$outboundSchema;
    /** @deprecated use `GetTopicResponseDtoOrganizationId$Outbound` instead. */
    export type Outbound = GetTopicResponseDtoOrganizationId$Outbound;
}

/** @internal */
export const GetTopicResponseDtoKey$inboundSchema: z.ZodType<
    GetTopicResponseDtoKey,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type GetTopicResponseDtoKey$Outbound = {};

/** @internal */
export const GetTopicResponseDtoKey$outboundSchema: z.ZodType<
    GetTopicResponseDtoKey$Outbound,
    z.ZodTypeDef,
    GetTopicResponseDtoKey
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTopicResponseDtoKey$ {
    /** @deprecated use `GetTopicResponseDtoKey$inboundSchema` instead. */
    export const inboundSchema = GetTopicResponseDtoKey$inboundSchema;
    /** @deprecated use `GetTopicResponseDtoKey$outboundSchema` instead. */
    export const outboundSchema = GetTopicResponseDtoKey$outboundSchema;
    /** @deprecated use `GetTopicResponseDtoKey$Outbound` instead. */
    export type Outbound = GetTopicResponseDtoKey$Outbound;
}

/** @internal */
export const GetTopicResponseDtoName$inboundSchema: z.ZodType<
    GetTopicResponseDtoName,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type GetTopicResponseDtoName$Outbound = {};

/** @internal */
export const GetTopicResponseDtoName$outboundSchema: z.ZodType<
    GetTopicResponseDtoName$Outbound,
    z.ZodTypeDef,
    GetTopicResponseDtoName
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTopicResponseDtoName$ {
    /** @deprecated use `GetTopicResponseDtoName$inboundSchema` instead. */
    export const inboundSchema = GetTopicResponseDtoName$inboundSchema;
    /** @deprecated use `GetTopicResponseDtoName$outboundSchema` instead. */
    export const outboundSchema = GetTopicResponseDtoName$outboundSchema;
    /** @deprecated use `GetTopicResponseDtoName$Outbound` instead. */
    export type Outbound = GetTopicResponseDtoName$Outbound;
}

/** @internal */
export const GetTopicResponseDto$inboundSchema: z.ZodType<
    GetTopicResponseDto,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        _environmentId: z.lazy(() => GetTopicResponseDtoEnvironmentId$inboundSchema),
        _id: z.lazy(() => GetTopicResponseDtoId$inboundSchema).optional(),
        _organizationId: z.lazy(() => GetTopicResponseDtoOrganizationId$inboundSchema),
        key: z.lazy(() => GetTopicResponseDtoKey$inboundSchema),
        name: z.lazy(() => GetTopicResponseDtoName$inboundSchema),
        subscribers: z.array(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            _environmentId: "environmentId",
            _id: "id",
            _organizationId: "organizationId",
        });
    });

/** @internal */
export type GetTopicResponseDto$Outbound = {
    _environmentId: GetTopicResponseDtoEnvironmentId$Outbound;
    _id?: GetTopicResponseDtoId$Outbound | undefined;
    _organizationId: GetTopicResponseDtoOrganizationId$Outbound;
    key: GetTopicResponseDtoKey$Outbound;
    name: GetTopicResponseDtoName$Outbound;
    subscribers: Array<string>;
};

/** @internal */
export const GetTopicResponseDto$outboundSchema: z.ZodType<
    GetTopicResponseDto$Outbound,
    z.ZodTypeDef,
    GetTopicResponseDto
> = z
    .object({
        environmentId: z.lazy(() => GetTopicResponseDtoEnvironmentId$outboundSchema),
        id: z.lazy(() => GetTopicResponseDtoId$outboundSchema).optional(),
        organizationId: z.lazy(() => GetTopicResponseDtoOrganizationId$outboundSchema),
        key: z.lazy(() => GetTopicResponseDtoKey$outboundSchema),
        name: z.lazy(() => GetTopicResponseDtoName$outboundSchema),
        subscribers: z.array(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            environmentId: "_environmentId",
            id: "_id",
            organizationId: "_organizationId",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTopicResponseDto$ {
    /** @deprecated use `GetTopicResponseDto$inboundSchema` instead. */
    export const inboundSchema = GetTopicResponseDto$inboundSchema;
    /** @deprecated use `GetTopicResponseDto$outboundSchema` instead. */
    export const outboundSchema = GetTopicResponseDto$outboundSchema;
    /** @deprecated use `GetTopicResponseDto$Outbound` instead. */
    export type Outbound = GetTopicResponseDto$Outbound;
}
