/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * User defined custom name and provided by the user to rename the topic.
 */
export type RenameTopicRequestDtoName = {};

export type RenameTopicRequestDto = {
    /**
     * User defined custom name and provided by the user to rename the topic.
     */
    name: RenameTopicRequestDtoName;
};

/** @internal */
export const RenameTopicRequestDtoName$inboundSchema: z.ZodType<
    RenameTopicRequestDtoName,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type RenameTopicRequestDtoName$Outbound = {};

/** @internal */
export const RenameTopicRequestDtoName$outboundSchema: z.ZodType<
    RenameTopicRequestDtoName$Outbound,
    z.ZodTypeDef,
    RenameTopicRequestDtoName
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RenameTopicRequestDtoName$ {
    /** @deprecated use `RenameTopicRequestDtoName$inboundSchema` instead. */
    export const inboundSchema = RenameTopicRequestDtoName$inboundSchema;
    /** @deprecated use `RenameTopicRequestDtoName$outboundSchema` instead. */
    export const outboundSchema = RenameTopicRequestDtoName$outboundSchema;
    /** @deprecated use `RenameTopicRequestDtoName$Outbound` instead. */
    export type Outbound = RenameTopicRequestDtoName$Outbound;
}

/** @internal */
export const RenameTopicRequestDto$inboundSchema: z.ZodType<
    RenameTopicRequestDto,
    z.ZodTypeDef,
    unknown
> = z.object({
    name: z.lazy(() => RenameTopicRequestDtoName$inboundSchema),
});

/** @internal */
export type RenameTopicRequestDto$Outbound = {
    name: RenameTopicRequestDtoName$Outbound;
};

/** @internal */
export const RenameTopicRequestDto$outboundSchema: z.ZodType<
    RenameTopicRequestDto$Outbound,
    z.ZodTypeDef,
    RenameTopicRequestDto
> = z.object({
    name: z.lazy(() => RenameTopicRequestDtoName$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RenameTopicRequestDto$ {
    /** @deprecated use `RenameTopicRequestDto$inboundSchema` instead. */
    export const inboundSchema = RenameTopicRequestDto$inboundSchema;
    /** @deprecated use `RenameTopicRequestDto$outboundSchema` instead. */
    export const outboundSchema = RenameTopicRequestDto$outboundSchema;
    /** @deprecated use `RenameTopicRequestDto$Outbound` instead. */
    export type Outbound = RenameTopicRequestDto$Outbound;
}
