/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * User defined description of the layout
 */
export type UpdateLayoutRequestDtoDescription = {};

/**
 * User defined custom key that will be a unique identifier for the Layout updated.
 */
export type UpdateLayoutRequestDtoIdentifier = {};

/**
 * User defined custom name and provided by the user that will name the Layout updated.
 */
export type UpdateLayoutRequestDtoName = {};

/**
 * User defined variables to render in the layout placeholders.
 */
export type Variables = {};

export type UpdateLayoutRequestDto = {
    /**
     * User defined content for the layout.
     */
    content?: string | undefined;
    /**
     * User defined description of the layout
     */
    description?: UpdateLayoutRequestDtoDescription | undefined;
    /**
     * User defined custom key that will be a unique identifier for the Layout updated.
     */
    identifier: UpdateLayoutRequestDtoIdentifier;
    /**
     * Variable that defines if the layout is chosen as default when creating a layout.
     */
    isDefault?: boolean | undefined;
    /**
     * User defined custom name and provided by the user that will name the Layout updated.
     */
    name?: UpdateLayoutRequestDtoName | undefined;
    /**
     * User defined variables to render in the layout placeholders.
     */
    variables?: Variables | undefined;
};

/** @internal */
export const UpdateLayoutRequestDtoDescription$inboundSchema: z.ZodType<
    UpdateLayoutRequestDtoDescription,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutRequestDtoDescription$Outbound = {};

/** @internal */
export const UpdateLayoutRequestDtoDescription$outboundSchema: z.ZodType<
    UpdateLayoutRequestDtoDescription$Outbound,
    z.ZodTypeDef,
    UpdateLayoutRequestDtoDescription
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutRequestDtoDescription$ {
    /** @deprecated use `UpdateLayoutRequestDtoDescription$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutRequestDtoDescription$inboundSchema;
    /** @deprecated use `UpdateLayoutRequestDtoDescription$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutRequestDtoDescription$outboundSchema;
    /** @deprecated use `UpdateLayoutRequestDtoDescription$Outbound` instead. */
    export type Outbound = UpdateLayoutRequestDtoDescription$Outbound;
}

/** @internal */
export const UpdateLayoutRequestDtoIdentifier$inboundSchema: z.ZodType<
    UpdateLayoutRequestDtoIdentifier,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutRequestDtoIdentifier$Outbound = {};

/** @internal */
export const UpdateLayoutRequestDtoIdentifier$outboundSchema: z.ZodType<
    UpdateLayoutRequestDtoIdentifier$Outbound,
    z.ZodTypeDef,
    UpdateLayoutRequestDtoIdentifier
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutRequestDtoIdentifier$ {
    /** @deprecated use `UpdateLayoutRequestDtoIdentifier$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutRequestDtoIdentifier$inboundSchema;
    /** @deprecated use `UpdateLayoutRequestDtoIdentifier$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutRequestDtoIdentifier$outboundSchema;
    /** @deprecated use `UpdateLayoutRequestDtoIdentifier$Outbound` instead. */
    export type Outbound = UpdateLayoutRequestDtoIdentifier$Outbound;
}

/** @internal */
export const UpdateLayoutRequestDtoName$inboundSchema: z.ZodType<
    UpdateLayoutRequestDtoName,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutRequestDtoName$Outbound = {};

/** @internal */
export const UpdateLayoutRequestDtoName$outboundSchema: z.ZodType<
    UpdateLayoutRequestDtoName$Outbound,
    z.ZodTypeDef,
    UpdateLayoutRequestDtoName
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutRequestDtoName$ {
    /** @deprecated use `UpdateLayoutRequestDtoName$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutRequestDtoName$inboundSchema;
    /** @deprecated use `UpdateLayoutRequestDtoName$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutRequestDtoName$outboundSchema;
    /** @deprecated use `UpdateLayoutRequestDtoName$Outbound` instead. */
    export type Outbound = UpdateLayoutRequestDtoName$Outbound;
}

/** @internal */
export const Variables$inboundSchema: z.ZodType<Variables, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type Variables$Outbound = {};

/** @internal */
export const Variables$outboundSchema: z.ZodType<Variables$Outbound, z.ZodTypeDef, Variables> =
    z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Variables$ {
    /** @deprecated use `Variables$inboundSchema` instead. */
    export const inboundSchema = Variables$inboundSchema;
    /** @deprecated use `Variables$outboundSchema` instead. */
    export const outboundSchema = Variables$outboundSchema;
    /** @deprecated use `Variables$Outbound` instead. */
    export type Outbound = Variables$Outbound;
}

/** @internal */
export const UpdateLayoutRequestDto$inboundSchema: z.ZodType<
    UpdateLayoutRequestDto,
    z.ZodTypeDef,
    unknown
> = z.object({
    content: z.string().optional(),
    description: z.lazy(() => UpdateLayoutRequestDtoDescription$inboundSchema).optional(),
    identifier: z.lazy(() => UpdateLayoutRequestDtoIdentifier$inboundSchema),
    isDefault: z.boolean().optional(),
    name: z.lazy(() => UpdateLayoutRequestDtoName$inboundSchema).optional(),
    variables: z.lazy(() => Variables$inboundSchema).optional(),
});

/** @internal */
export type UpdateLayoutRequestDto$Outbound = {
    content?: string | undefined;
    description?: UpdateLayoutRequestDtoDescription$Outbound | undefined;
    identifier: UpdateLayoutRequestDtoIdentifier$Outbound;
    isDefault?: boolean | undefined;
    name?: UpdateLayoutRequestDtoName$Outbound | undefined;
    variables?: Variables$Outbound | undefined;
};

/** @internal */
export const UpdateLayoutRequestDto$outboundSchema: z.ZodType<
    UpdateLayoutRequestDto$Outbound,
    z.ZodTypeDef,
    UpdateLayoutRequestDto
> = z.object({
    content: z.string().optional(),
    description: z.lazy(() => UpdateLayoutRequestDtoDescription$outboundSchema).optional(),
    identifier: z.lazy(() => UpdateLayoutRequestDtoIdentifier$outboundSchema),
    isDefault: z.boolean().optional(),
    name: z.lazy(() => UpdateLayoutRequestDtoName$outboundSchema).optional(),
    variables: z.lazy(() => Variables$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutRequestDto$ {
    /** @deprecated use `UpdateLayoutRequestDto$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutRequestDto$inboundSchema;
    /** @deprecated use `UpdateLayoutRequestDto$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutRequestDto$outboundSchema;
    /** @deprecated use `UpdateLayoutRequestDto$Outbound` instead. */
    export type Outbound = UpdateLayoutRequestDto$Outbound;
}
