/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export type UpdateLayoutResponseDtoCreatorId = {};

export type UpdateLayoutResponseDtoEnvironmentId = {};

export type UpdateLayoutResponseDtoId = {};

export type UpdateLayoutResponseDtoOrganizationId = {};

export const UpdateLayoutResponseDtoChannel = {
    InApp: "in_app",
    Email: "email",
    Sms: "sms",
    Chat: "chat",
    Push: "push",
} as const;
export type UpdateLayoutResponseDtoChannel = ClosedEnum<typeof UpdateLayoutResponseDtoChannel>;

export type UpdateLayoutResponseDtoDescription = {};

export type UpdateLayoutResponseDtoIdentifier = {};

export type UpdateLayoutResponseDtoName = {};

export type UpdateLayoutResponseDto = {
    creatorId: UpdateLayoutResponseDtoCreatorId;
    environmentId: UpdateLayoutResponseDtoEnvironmentId;
    id?: UpdateLayoutResponseDtoId | undefined;
    organizationId: UpdateLayoutResponseDtoOrganizationId;
    parentId?: string | undefined;
    channel: UpdateLayoutResponseDtoChannel;
    content: string;
    contentType: string;
    createdAt?: string | undefined;
    description?: UpdateLayoutResponseDtoDescription | undefined;
    identifier: UpdateLayoutResponseDtoIdentifier;
    isDefault: boolean;
    isDeleted: boolean;
    name: UpdateLayoutResponseDtoName;
    updatedAt?: string | undefined;
    variables?: Array<string> | undefined;
};

/** @internal */
export const UpdateLayoutResponseDtoCreatorId$inboundSchema: z.ZodType<
    UpdateLayoutResponseDtoCreatorId,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutResponseDtoCreatorId$Outbound = {};

/** @internal */
export const UpdateLayoutResponseDtoCreatorId$outboundSchema: z.ZodType<
    UpdateLayoutResponseDtoCreatorId$Outbound,
    z.ZodTypeDef,
    UpdateLayoutResponseDtoCreatorId
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDtoCreatorId$ {
    /** @deprecated use `UpdateLayoutResponseDtoCreatorId$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDtoCreatorId$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoCreatorId$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDtoCreatorId$outboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoCreatorId$Outbound` instead. */
    export type Outbound = UpdateLayoutResponseDtoCreatorId$Outbound;
}

/** @internal */
export const UpdateLayoutResponseDtoEnvironmentId$inboundSchema: z.ZodType<
    UpdateLayoutResponseDtoEnvironmentId,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutResponseDtoEnvironmentId$Outbound = {};

/** @internal */
export const UpdateLayoutResponseDtoEnvironmentId$outboundSchema: z.ZodType<
    UpdateLayoutResponseDtoEnvironmentId$Outbound,
    z.ZodTypeDef,
    UpdateLayoutResponseDtoEnvironmentId
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDtoEnvironmentId$ {
    /** @deprecated use `UpdateLayoutResponseDtoEnvironmentId$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDtoEnvironmentId$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoEnvironmentId$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDtoEnvironmentId$outboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoEnvironmentId$Outbound` instead. */
    export type Outbound = UpdateLayoutResponseDtoEnvironmentId$Outbound;
}

/** @internal */
export const UpdateLayoutResponseDtoId$inboundSchema: z.ZodType<
    UpdateLayoutResponseDtoId,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutResponseDtoId$Outbound = {};

/** @internal */
export const UpdateLayoutResponseDtoId$outboundSchema: z.ZodType<
    UpdateLayoutResponseDtoId$Outbound,
    z.ZodTypeDef,
    UpdateLayoutResponseDtoId
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDtoId$ {
    /** @deprecated use `UpdateLayoutResponseDtoId$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDtoId$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoId$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDtoId$outboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoId$Outbound` instead. */
    export type Outbound = UpdateLayoutResponseDtoId$Outbound;
}

/** @internal */
export const UpdateLayoutResponseDtoOrganizationId$inboundSchema: z.ZodType<
    UpdateLayoutResponseDtoOrganizationId,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutResponseDtoOrganizationId$Outbound = {};

/** @internal */
export const UpdateLayoutResponseDtoOrganizationId$outboundSchema: z.ZodType<
    UpdateLayoutResponseDtoOrganizationId$Outbound,
    z.ZodTypeDef,
    UpdateLayoutResponseDtoOrganizationId
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDtoOrganizationId$ {
    /** @deprecated use `UpdateLayoutResponseDtoOrganizationId$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDtoOrganizationId$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoOrganizationId$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDtoOrganizationId$outboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoOrganizationId$Outbound` instead. */
    export type Outbound = UpdateLayoutResponseDtoOrganizationId$Outbound;
}

/** @internal */
export const UpdateLayoutResponseDtoChannel$inboundSchema: z.ZodNativeEnum<
    typeof UpdateLayoutResponseDtoChannel
> = z.nativeEnum(UpdateLayoutResponseDtoChannel);

/** @internal */
export const UpdateLayoutResponseDtoChannel$outboundSchema: z.ZodNativeEnum<
    typeof UpdateLayoutResponseDtoChannel
> = UpdateLayoutResponseDtoChannel$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDtoChannel$ {
    /** @deprecated use `UpdateLayoutResponseDtoChannel$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDtoChannel$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoChannel$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDtoChannel$outboundSchema;
}

/** @internal */
export const UpdateLayoutResponseDtoDescription$inboundSchema: z.ZodType<
    UpdateLayoutResponseDtoDescription,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutResponseDtoDescription$Outbound = {};

/** @internal */
export const UpdateLayoutResponseDtoDescription$outboundSchema: z.ZodType<
    UpdateLayoutResponseDtoDescription$Outbound,
    z.ZodTypeDef,
    UpdateLayoutResponseDtoDescription
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDtoDescription$ {
    /** @deprecated use `UpdateLayoutResponseDtoDescription$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDtoDescription$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoDescription$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDtoDescription$outboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoDescription$Outbound` instead. */
    export type Outbound = UpdateLayoutResponseDtoDescription$Outbound;
}

/** @internal */
export const UpdateLayoutResponseDtoIdentifier$inboundSchema: z.ZodType<
    UpdateLayoutResponseDtoIdentifier,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutResponseDtoIdentifier$Outbound = {};

/** @internal */
export const UpdateLayoutResponseDtoIdentifier$outboundSchema: z.ZodType<
    UpdateLayoutResponseDtoIdentifier$Outbound,
    z.ZodTypeDef,
    UpdateLayoutResponseDtoIdentifier
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDtoIdentifier$ {
    /** @deprecated use `UpdateLayoutResponseDtoIdentifier$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDtoIdentifier$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoIdentifier$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDtoIdentifier$outboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoIdentifier$Outbound` instead. */
    export type Outbound = UpdateLayoutResponseDtoIdentifier$Outbound;
}

/** @internal */
export const UpdateLayoutResponseDtoName$inboundSchema: z.ZodType<
    UpdateLayoutResponseDtoName,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UpdateLayoutResponseDtoName$Outbound = {};

/** @internal */
export const UpdateLayoutResponseDtoName$outboundSchema: z.ZodType<
    UpdateLayoutResponseDtoName$Outbound,
    z.ZodTypeDef,
    UpdateLayoutResponseDtoName
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDtoName$ {
    /** @deprecated use `UpdateLayoutResponseDtoName$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDtoName$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoName$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDtoName$outboundSchema;
    /** @deprecated use `UpdateLayoutResponseDtoName$Outbound` instead. */
    export type Outbound = UpdateLayoutResponseDtoName$Outbound;
}

/** @internal */
export const UpdateLayoutResponseDto$inboundSchema: z.ZodType<
    UpdateLayoutResponseDto,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        _creatorId: z.lazy(() => UpdateLayoutResponseDtoCreatorId$inboundSchema),
        _environmentId: z.lazy(() => UpdateLayoutResponseDtoEnvironmentId$inboundSchema),
        _id: z.lazy(() => UpdateLayoutResponseDtoId$inboundSchema).optional(),
        _organizationId: z.lazy(() => UpdateLayoutResponseDtoOrganizationId$inboundSchema),
        _parentId: z.string().optional(),
        channel: UpdateLayoutResponseDtoChannel$inboundSchema,
        content: z.string(),
        contentType: z.string(),
        createdAt: z.string().optional(),
        description: z.lazy(() => UpdateLayoutResponseDtoDescription$inboundSchema).optional(),
        identifier: z.lazy(() => UpdateLayoutResponseDtoIdentifier$inboundSchema),
        isDefault: z.boolean(),
        isDeleted: z.boolean(),
        name: z.lazy(() => UpdateLayoutResponseDtoName$inboundSchema),
        updatedAt: z.string().optional(),
        variables: z.array(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            _creatorId: "creatorId",
            _environmentId: "environmentId",
            _id: "id",
            _organizationId: "organizationId",
            _parentId: "parentId",
        });
    });

/** @internal */
export type UpdateLayoutResponseDto$Outbound = {
    _creatorId: UpdateLayoutResponseDtoCreatorId$Outbound;
    _environmentId: UpdateLayoutResponseDtoEnvironmentId$Outbound;
    _id?: UpdateLayoutResponseDtoId$Outbound | undefined;
    _organizationId: UpdateLayoutResponseDtoOrganizationId$Outbound;
    _parentId?: string | undefined;
    channel: string;
    content: string;
    contentType: string;
    createdAt?: string | undefined;
    description?: UpdateLayoutResponseDtoDescription$Outbound | undefined;
    identifier: UpdateLayoutResponseDtoIdentifier$Outbound;
    isDefault: boolean;
    isDeleted: boolean;
    name: UpdateLayoutResponseDtoName$Outbound;
    updatedAt?: string | undefined;
    variables?: Array<string> | undefined;
};

/** @internal */
export const UpdateLayoutResponseDto$outboundSchema: z.ZodType<
    UpdateLayoutResponseDto$Outbound,
    z.ZodTypeDef,
    UpdateLayoutResponseDto
> = z
    .object({
        creatorId: z.lazy(() => UpdateLayoutResponseDtoCreatorId$outboundSchema),
        environmentId: z.lazy(() => UpdateLayoutResponseDtoEnvironmentId$outboundSchema),
        id: z.lazy(() => UpdateLayoutResponseDtoId$outboundSchema).optional(),
        organizationId: z.lazy(() => UpdateLayoutResponseDtoOrganizationId$outboundSchema),
        parentId: z.string().optional(),
        channel: UpdateLayoutResponseDtoChannel$outboundSchema,
        content: z.string(),
        contentType: z.string(),
        createdAt: z.string().optional(),
        description: z.lazy(() => UpdateLayoutResponseDtoDescription$outboundSchema).optional(),
        identifier: z.lazy(() => UpdateLayoutResponseDtoIdentifier$outboundSchema),
        isDefault: z.boolean(),
        isDeleted: z.boolean(),
        name: z.lazy(() => UpdateLayoutResponseDtoName$outboundSchema),
        updatedAt: z.string().optional(),
        variables: z.array(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            creatorId: "_creatorId",
            environmentId: "_environmentId",
            id: "_id",
            organizationId: "_organizationId",
            parentId: "_parentId",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateLayoutResponseDto$ {
    /** @deprecated use `UpdateLayoutResponseDto$inboundSchema` instead. */
    export const inboundSchema = UpdateLayoutResponseDto$inboundSchema;
    /** @deprecated use `UpdateLayoutResponseDto$outboundSchema` instead. */
    export const outboundSchema = UpdateLayoutResponseDto$outboundSchema;
    /** @deprecated use `UpdateLayoutResponseDto$Outbound` instead. */
    export type Outbound = UpdateLayoutResponseDto$Outbound;
}
